### ISSUE TITLE
Add wheel package file format support

### ISSUE THREAD

**Issue by mnixry** [mina86/pygtrie#3]
Some special runtimes, for example, [`PyScript`](https://pyscript.net/) only accept [wheel format of package](https://github.com/pyscript/pyscript/blob/main/docs/tutorials/getting-started.md#the-py-env-tag).
Since this package is a pure-python implementation, in this case, we can easily build the `.whl` package by `python setup.py bdist_wheel` command before you publish.

Anyway, thank you for your continuously maintain this package.

**Comment by mina86** [comment]
I’m not familiar with PyScript or wheel files so bare with me.  How does it help that I have a .whl file in my dist directory? I’m not sure I understand what you’re proposing.

**Comment by mnixry** [comment]
Sorry for my poor explanation

If you have a `.whl` in your dist directory, it will be released together with `.tar.gz` in a new version. You can find that in the [file panel](https://pypi.org/project/pygtrie/#files) in PyPI website.

Many of Python packages, are published both `.whl` and `.tar.gz` format package in PyPI. 
The `.whl` file indicates it is “Built Distributions” can be installed directly (includes necessary dependencies and metadata). 
But the `.tar.gz` file means it is “Source Distribution” that requires some post-processing steps (For `pygtrie`, It is execute `python setup.py install`), almost no differ from pull the code from GitHub and install.

Even if there are pure-python packages, which doesn't need some complex compile steps, we still need to build and upload a `.whl` file to indicate we have a “Built” distribution with all required metadata. (PyScript only have an over simplified pip implementation, so it can only accept a built distribution)
For example, [requests](https://pypi.org/project/requests/#files) are having both of them.

So I think publishing a package with `.whl` can not only bring compatibility to PyScript users, but also standardizes the package-publishing process. That will benefit many `pygtrie` users experiences implicitly.

**Comment by mina86** [comment]
Got it, so it's really a change in release process.

I really hate Python packaging.

And wasn't setuptools deprecated or something? Or was it distutils...  With
current setup.py bdist_wheel isn't actually available because it doesn't
use setuptools. I guess I'll have to now take a look into that...
